### ISSUE TITLE
Formal Education and NanoTrasen employment history are swapped

### ISSUE THREAD

**Issue by Chada-1** [Lohikar/AuroraRecordGenerator#1]
Title. If you leave the mouse over one of them it'll bring up the opposite. I'm no coder but this *looks* like it'd be an easy fix. This is posted on request for bookkeeping.

**Comment by CodePanter** [comment]
I made a pull request that should fix it. Internally, it is only the tooltip descriptions that were swapped, not any actual logic (as far as I can see).

**Comment by Lohikar** [comment]
Fixed by #2.
